Refactor: DRY: Relocate useful git functions to landonb/sh-git-nubs.

diff --git a/bin/git-my-merge-status b/bin/git-my-merge-status
--- a/bin/git-my-merge-status
+++ b/bin/git-my-merge-status
@@ -384,6 +384,49 @@ my_merge_status_config () {
 
 # ***
 
+source_deps () {
+  local thispth="$1"
+  local prefix=""
+  local depsnok=false
+
+  _source_it () {
+    local prfx="${1:-.}"
+    local depd="${2:-.}"
+    local file="${3:-.}"
+    local path="${prfx}/${depd}/${file}"
+    if command -v "${file}" > /dev/null; then
+      # Use version found on PATH.
+      . "${file}"
+    elif [ -f "${path}" ]; then
+      # Fallback on local deps/ copy.
+      # NOTE: `dash` complains if missing './'.
+      . "${path}"
+    else
+      local depstxt=''
+      [ "${prfx}" != "." ] && depstxt="in ‘${prfx}/${depd}’ or "
+      >&2 echo "MISSING: ‘${file}’ not found ${depstxt}on PATH."
+      depsnok=true
+    fi
+  }
+
+  # Allow user to symlink executables and not libraries.
+  prefix="$(dirname -- "$(readlink -e -- "${thispth}")")"
+
+  #                                                                 |
+  # *** end boilerplate. -------------------------------------------|
+
+  # Load git_* functions.
+  # https://github.com/landonb/sh-git-nubs
+  _source_it "${prefix}" "../deps/sh-git-nubs/bin" "git-nubs.sh"
+
+  # *** finish with boilerplate. -----------------------------------|
+  #                                                                 |
+
+  ! ${depsnok}
+}
+
+# ***
+
 python_get_distribution () {
   local pkgname="$1"
   /usr/bin/env python3 -c \
@@ -435,39 +478,6 @@ fg_red () {
 
 fg_tan () {
   printf "\033[38;2;215;175;95m"
-}
-
-# ***
-
-git_branch_name () {
-  local project_root="$(git rev-parse --show-toplevel)"
-  # Note that $(git rev-parse HEAD) returns the hash, not the name,
-  # so we add the option, --abbrev-ref.
-  # - But first! check there's actually a branch, i.e., if `git init`
-  #   but no `git commit`, rev-parse prints error.
-  # - Note that `test ""` returns false; `test "foo"` returns true.
-  if [ ! "$(command ls -A "${project_root}/.git/refs/heads")" ]; then
-    echo "<?!>"
-    return
-  fi
-  local branch_name=$(git rev-parse --abbrev-ref HEAD)
-  echo "${branch_name}"
-}
-
-branch_exists () {
-  local branch_name="${1:-${GITFLU_MYST_AT_BRANCH}}"
-  git show-ref --verify --quiet refs/heads/${branch_name}
-}
-
-remote_exists () {
-  local remote="$1"
-  git remote get-url ${remote} &> /dev/null
-}
-
-remote_branch_exists () {
-  local remote="$1"
-  local branch="$2"
-  git show-branch remotes/${remote}/${branch} &> /dev/null
 }
 
 # ***
@@ -577,73 +587,6 @@ warn_up_not_ancestor () {
 }
 
 # ***
-
-GITFLU_RE_VERSION_TAG='[v0-9][0-9.]*'
-
-git_last_version_tag_describe () {
-  # By default, git-describe returns a commit-ish object representing the same
-  # commit as the referenced commit (which defaults to HEAD). The described name
-  # is the tag name, followed by the number of commits between it and the commit
-  # referenced, and finally suffixed with a 'g' and part of the referenced SHA.
-  # E.g., `git describe --tags --long --match '[v0-9][0-9.]*'` might return:
-  #       "0.12.0-828-g0266e06".
-  # So specify an --abbrev=0 to "suppress long format, only showing the closest tag."
-  # And note that I don't see a difference with --long or not. Not sure why I added.
-  # But it cannot be used with --abbrev=0. So easy to decide what to do. Not use it.
-  git describe --tags --abbrev=0 --match "${GITFLU_RE_VERSION_TAG}" 2> /dev/null
-}
-
-git_last_version_tag_describe_safe () {
-  git_last_version_tag_describe || echo '0.0.0-✗-g0000000'
-}
-
-# Unused...
-if false; then
-  GITFLU_RE_LONG_TAG_PARTS='([^-]+)-([^-]+)-(.*)'
-
-  git_last_version_name () {
-    local described="$(git_last_version_tag_describe_safe)"
-    echo ${described} | /bin/sed -E "s/${GITFLU_RE_LONG_TAG_PARTS}/\1/g"
-  }
-
-  git_last_version_dist () {
-    local described="$(git_last_version_tag_describe_safe)"
-    echo ${described} | /bin/sed -E "s/${GITFLU_RE_LONG_TAG_PARTS}/\2/g"
-  }
-
-  git_last_version_absent () {
-    local distance="$(git_last_version_dist)"
-    [ "${distance}" = '✗' ]
-  }
-fi
-
-git_last_version_epoch_ts () {
-  # Note that the "described" tag output (e.g., 0.12.0-828-g0266e06) is a
-  # valid revision (per `man 7 gitrevisions`), which can be fed to git-log.
-  # - And to compute a time delta from then to now, get seconds since epoch:
-  #   git help log:
-  #     %at: author date, UNIX timestamp
-  git --no-pager \
-    log -1 \
-    --format=%at \
-    "$(git_last_version_tag_describe_safe)" \
-    2> /dev/null
-}
-
-git_since_init_epoch_ts () {
-  # Note that the "described" tag output (e.g., 0.12.0-828-g0266e06) is a
-  # valid revision (per `man 7 gitrevisions`), which can be fed to git-log.
-  # - And to compute a time delta from then to now, get seconds since epoch:
-  #   git help log:
-  #     %at: author date, UNIX timestamp
-  # NOTE: rev-list outputs in reverse chronological order, so oldest commit
-  #       is last; use tail to grab it.
-  git --no-pager \
-    log -1 \
-    --format=%at \
-    "$(git rev-list --max-parents=0 HEAD | tail -1)" \
-    2> /dev/null
-}
 
 python_prettify_elapsed () {
   local seconds="${1:-0}"
@@ -908,7 +851,7 @@ prepare_icon_synced_remote () {
   # Note that we don't want to make a network call, so avoiding, e.g.,
   #   git show-ref --verify --quiet refs/remotes/${remote}/${at_branch}
   # and well as `git ls-remote`.
-  if ! remote_branch_exists "${remote}" "${at_branch}"; then
+  if ! git_remote_branch_exists "${remote}" "${at_branch}"; then
     # Default to placeholder "icon" (blank spaces).
     sync_icon="$(fill_placeholder "1")"
     remote_branch_absent=true
@@ -1001,7 +944,7 @@ prepare_icons_remotes () {
     shift 3
 
     local re_icon
-    if remote_exists "${remote}"; then
+    if git_remote_exists "${remote}"; then
       re_icon="$(prepare_icon_synced_remote "${remote}" "${iconok}" "${iconxx}" "${diffco}")"
       let "syncodes |= $?"
     elif ${GITFLU_MYST_ALIGN_COLS}; then
@@ -1014,7 +957,7 @@ prepare_icons_remotes () {
       re_icons="${re_icons}${GITFLU_MYST_SEPARATE_REMOTES}${re_icon}"
     fi
     # Only change diffco (previous reference branch) if it exists.
-    if remote_branch_exists "${remote}" "${currbr}"; then
+    if git_remote_branch_exists "${remote}" "${currbr}"; then
       diffco="${remote}/${currbr}"
     fi
   done
@@ -1172,7 +1115,9 @@ prepare_branch_report () {
   GITFLU_MYST_AT_BRANCH="$(git_branch_name)"
 
   GITFLU_MYST_UP_BRANCH="$(branch_ancestor "${GITFLU_MYST_AT_BRANCH}")"
-  while [ -n "${GITFLU_MYST_UP_BRANCH}" ] && ! branch_exists "${GITFLU_MYST_UP_BRANCH}"; do
+  while [ -n "${GITFLU_MYST_UP_BRANCH}" ] \
+        && ! git_branch_exists "${GITFLU_MYST_UP_BRANCH}" \
+  ; do
     GITFLU_MYST_UP_BRANCH="$(branch_ancestor "${GITFLU_MYST_UP_BRANCH}")"
   done
 
@@ -1217,6 +1162,7 @@ my_merge_status_report () {
 # ***
 
 main () {
+  source_deps "${BASH_SOURCE[0]}" || exit 1
   local before_cd="$(pwd -L)"
   # So that a git alias works, which run !commands from top-level, cd maybe.
   [ -n "${GIT_PREFIX}" ] && cd "${GIT_PREFIX}"
