Harden: Normalize shell dependency loading boilerplate
- REFER:

  https://github.com/DepoXy/sh-source-deps-template#🤞

diff --git a/bin/git-my-merge-status b/bin/git-my-merge-status
--- a/bin/git-my-merge-status
+++ b/bin/git-my-merge-status
@@ -627,45 +627,112 @@ my_merge_status_config () {
 # *** <beg boilerplate `source_deps`: ------------------------------|
 #                                                                   |
 
-source_deps () {
-  local thispth="$1"
-  local prefix="."
-  local depsnok=false
+_git_my_merge_status__this_filename="git-my-merge-status"
 
-  _source_it () {
-    local prfx="${1:-.}"
-    local depd="${2:-.}"
-    local file="${3:-.}"
-    local path="${prfx}/${depd}/${file}"
-    if command -v "${file}" > /dev/null; then
-      # Use version found on PATH.
-      . "${file}"
-    elif [ -f "${path}" ]; then
-      # Fallback on local deps/ copy.
-      # NOTE: `dash` complains if missing './'.
-      . "${path}"
-    else
-      local depstxt=''
-      [ "${prfx}" != "." ] && depstxt="in ‘${prfx}/${depd}’ or "
-      >&2 echo "MISSING: ‘${file}’ not found ${depstxt}on PATH."
-      depsnok=true
-    fi
-  }
+_git_my_merge_status__source_deps () {
+  local sourced_all=true
 
-  [ -n "${thispth}" ] && prefix="$(dirname -- "$(realpath -- "${thispth}")")"
+  # On Bash, user can source this file from anywhere.
+  # - If not Bash, user must `cd` to this file's parent directory first.
+  local prefix="$(dirname -- "${_git_my_merge_status__this_fullpath}")"
+
+  # USAGE: Load dependencies using path relative to this file, e.g.:
+  #   _source_file "${prefix}" "../deps/path/to/lib" "dependency.sh"
 
   #                                                                 |
   # *** stop boilerplate> ------------------------------------------|
 
   # Load git_* funcs (e.g., git_branch_name), vars (GITNUBS_RE_VERSPARTS), etc.
   #  https://github.com/landonb/sh-git-nubs
-  _source_it "${prefix}" "../deps/sh-git-nubs/lib" "git-nubs.sh"
+  _git_my_merge_status__source_file "${prefix}" "../deps/sh-git-nubs/lib" "git-nubs.sh"
 
   # *** <more boilerplate: -----------------------------------------|
   #                                                                 |
 
-  ! ${depsnok}
+  ${sourced_all}
 }
+
+_git_my_merge_status__smells_like_bash () { declare -p BASH_SOURCE > /dev/null 2>&1; }
+
+_git_my_merge_status__print_this_fullpath () {
+  if _git_my_merge_status__smells_like_bash; then
+    echo "$(realpath -- "${BASH_SOURCE[0]}")"
+  elif [ "$(basename -- "$0")" = "${_git_my_merge_status__this_filename}" ]; then
+    # Assumes this script being executed, and $0 is its path.
+    echo "$(realpath -- "$0")"
+  else
+    # Assumes cwd is this script's parent directory.
+    echo "$(realpath -- "${_git_my_merge_status__this_filename}")"
+  fi
+}
+
+_git_my_merge_status__this_fullpath="$(_git_my_merge_status__print_this_fullpath)"
+
+_git_my_merge_status__shell_sourced () {
+  [ "$(realpath -- "$0")" != "${_git_my_merge_status__this_fullpath}" ]
+}
+
+_git_my_merge_status__source_file () {
+  local prfx="${1:-.}"
+  local depd="${2:-.}"
+  local file="${3:-.}"
+
+  local deps_dir="${prfx}/${depd}"
+  local deps_path="${deps_dir}/${file}"
+
+  # Just in case sourced file overwrites top-level `_git_my_merge_status__this_filename`,
+  # cache our copy, should we need it for an error message.
+  local _this_file_name="${_git_my_merge_status__this_filename}"
+
+  if [ -f "${deps_path}" ]; then
+    # SAVVY: Source files from their dirs, so they can find their deps.
+    local before_cd="$(pwd -L)"
+    cd "${deps_dir}"
+    # SAVVY: If errexit, error while sourcing kills process immediately,
+    # and error you see might indicate this source file, but the line
+    # number for the file being sourced. E.g.,
+    #   /path/to/bin/myapp: 442: export: Illegal option -f
+    # where `442` is line number from, e.g., 'deps/lib/dep.sh'.
+    if ! . "${deps_path}"; then
+      >&2 echo "ERROR: Dependency ‘${file}’ returned nonzero when sourced"
+      sourced_all=false
+    fi
+    cd "${before_cd}"
+  else
+    local depstxt=""
+    [ "${prfx}" = "." ] || depstxt="in ‘${deps_dir}’ or "
+    >&2 echo "ERROR: ‘${file}’ not found under ‘${deps_dir}’"
+    if _git_my_merge_status__smells_like_bash; then
+      >&2 echo "- GAFFE: This looks like an error with the ‘_git_my_merge_status__source_file’ arguments"
+    else
+      >&2 echo "- HINT: You must source ‘${_this_file_name}’ from its parent directory"
+    fi
+    sourced_all=false
+  fi
+}
+
+# BONUS: You can use these aliases instead of the uniquely-named functions,
+# just be aware not to call any alias after calling _source_deps.
+_shell_sourced () { _git_my_merge_status__shell_sourced; }
+_source_deps () { _git_my_merge_status__source_deps; }
+
+_git_my_merge_status__source_deps_unset_cleanup () {
+  unset -v _git_my_merge_status__this_filename
+  unset -f _git_my_merge_status__print_this_fullpath
+  unset -f _git_my_merge_status__shell_sourced
+  unset -f _shell_sourced
+  unset -f _git_my_merge_status__smells_like_bash
+  unset -f _git_my_merge_status__source_deps
+  unset -f _source_deps
+  unset -f _git_my_merge_status__source_deps_unset_cleanup
+  unset -f _git_my_merge_status__source_file
+}
+
+# USAGE: When this file is being executed, before doing stuff, call:
+#   _source_deps
+# - When this file is being sourced, call both:
+#   _source_deps
+#   _git_my_merge_status__source_deps_unset_cleanup
 
 #                                                                   |
 # *** end boilerplate `source_deps`> -------------------------------|
@@ -1599,7 +1666,7 @@ my_merge_status_report () {
 # ***
 
 main () {
-  source_deps "${BASH_SOURCE[0]}" || exit 1
+  _source_deps || exit 1
   local before_cd="$(pwd -L)"
   # So that a git alias works, which run !commands from top-level, cd maybe.
   [ -n "${GIT_PREFIX}" ] && cd "${GIT_PREFIX}"
@@ -1609,7 +1676,12 @@ main () {
   cd "${before_cd}"
 }
 
-if [ "$0" = "${BASH_SOURCE[0]}" ]; then
-  main "${@}"
+if _shell_sourced; then
+  _source_deps
+else
+  main "$@"
 fi
+
+_git_my_merge_status__source_deps_unset_cleanup
+unset -f main
 
